### ISSUE TITLE
Person class refactor

### ISSUE THREAD

**Issue by barisener** [KaygusuzBK/phonebook#4]
Buradaki person classındaki addToPerson fonksiyonu burada olmamalı. Bunun yerine personListesindeki addToList kullanılarak kişiler listeye eklenmeli.

**Comment by KaygusuzBK** [comment]
Refactor yapıldı. Person classındaki addToPerson fonksiyonu çıkarıldı . Artık Personlist classındaki addToList kullanılarak kişiler listelendi.
